/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andrea.hyder' at '4/15/18 4:06 PM' with Gradle 2.6
 *
 * @author andrea.hyder, @date 4/15/18 4:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
